# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RandomStart_cpp <- function(input_vector) {
    .Call('_ClusterSSCA_RandomStart_cpp', PACKAGE = 'ClusterSSCA', input_vector)
}

MatrixCenter_cpp <- function(input_matrix, center, scale) {
    .Call('_ClusterSSCA_MatrixCenter_cpp', PACKAGE = 'ClusterSSCA', input_matrix, center, scale)
}

sca_common_cpp <- function(data_con, common) {
    .Call('_ClusterSSCA_sca_common_cpp', PACKAGE = 'ClusterSSCA', data_con, common)
}

csca_cpp <- function(xc, nvar, nblock, all_components, ncluster, iteration) {
    .Call('_ClusterSSCA_csca_cpp', PACKAGE = 'ClusterSSCA', xc, nvar, nblock, all_components, ncluster, iteration)
}

sparsedisco_cpp <- function(data_con, nvar, all_components, p, fixed_zeros, n_zeros) {
    .Call('_ClusterSSCA_sparsedisco_cpp', PACKAGE = 'ClusterSSCA', data_con, nvar, all_components, p, fixed_zeros, n_zeros)
}

IntSparseSca_rational_full_cpp <- function(data_con, nvar, nblock, all_components, initial, fixed_zeros, sparsity) {
    .Call('_ClusterSSCA_IntSparseSca_rational_full_cpp', PACKAGE = 'ClusterSSCA', data_con, nvar, nblock, all_components, initial, fixed_zeros, sparsity)
}

IntSparseSca_random_cpp <- function(data_con, nvar, nblock, all_components, fixed_zeros, sparsity) {
    .Call('_ClusterSSCA_IntSparseSca_random_cpp', PACKAGE = 'ClusterSSCA', data_con, nvar, nblock, all_components, fixed_zeros, sparsity)
}

cssca_quick_cpp <- function(data_con, nvar, nblock, common, distinct, ncluster, nrespondents, sparsity, feed, cutoff_prop) {
    .Call('_ClusterSSCA_cssca_quick_cpp', PACKAGE = 'ClusterSSCA', data_con, nvar, nblock, common, distinct, ncluster, nrespondents, sparsity, feed, cutoff_prop)
}

